# Add friend to user
POST http://localhost:4000/api/client/friend/308 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwNywiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMjA1NjMsImV4cCI6MTY5OTAyNzQ2M30.fSivaZxpdRb4moGm8vNocJVyZLxxugZvsu2W1NpBG88
###

# Delete friend from user
DELETE http://localhost:4000/api/client/friend/54 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMSwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NDk0MDQsImV4cCI6MTY5ODc1MDMwNH0.noL_PexjLgKrH31M5VqZo-5YNAnfBbautqVSUxc3dpw

###

# Get friends

GET http://localhost:4000/api/client/friends/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMSwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NTE2NzAsImV4cCI6MTY5ODc1MjU3MH0.LH4L5tIDmafLVET1xkuDfTLNkuiLnI69Cz_nFaCrVcI
###

# Check balance training
GET http://localhost:4000/api/client/balance-training/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMSwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NTMxNDksImV4cCI6MTY5ODc1NDA0OX0.2wwJItwIVPmszdiTY2LJqM-mUfp7C42IyB-Rj3kdHl4
###

# Use training

DELETE  http://localhost:4000/api/client/training/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMSwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NTMxNDksImV4cCI6MTY5ODc1NDA0OX0.2wwJItwIVPmszdiTY2LJqM-mUfp7C42IyB-Rj3kdHl4
###


# Post feedback

POST http://localhost:4000/api/feedbacks/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMSwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTg3NTMxNDksImV4cCI6MTY5ODc1NDA0OX0.2wwJItwIVPmszdiTY2LJqM-mUfp7C42IyB-Rj3kdHl4
Content-Type: application/json

{
  "trainingId": 2,
  "rating": 4,
  "text": "Вроде нормальная тренировка, но изюминки нету... Минимум 100 символов это сильно! Может учат нас печатать?"
}
###

# add Order training

POST http://localhost:4000/api/client/order HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwNiwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMTc2OTAsImV4cCI6MTY5OTAyNDU5MH0.RtuTsvsKuFarfw2_OgS3o9_z5Gy2CbEWom7KcsPt4IQ
Content-Type: application/json

{
  "type": "абонемент",
  "trainingId": 305,
  "price": 12,
  "quantity": 100,
  "typeOfPayment": "visa"
}
###

# # Reciving recomendations userroom list of trainining
# GET http://localhost:4000/api/user/recomendations HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTk0MzUwNywiZXhwIjoxNjg5OTQ0NDA3fQ.fYFoqatP9ZtErbZSdIeNna5FtK_S6eHOlmLS2BGTYfg
# {
#   "typesOfTraining": [],
#   "timeOfTraining": 1,
#   "levelOfExperience": "",
#   "caloryLosingPlanTotal": 1000
# }
# ###
