# Add friend to user
POST http://localhost:4000/api/client/friend/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWFib3JpMkBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNTU4LCJleHAiOjE2OTk0NTg0NTh9.vbiantt_n75BpFc2FU5nKNkxsmJN-daH74_f7OLRnwU
###

# Delete friend from user
DELETE http://localhost:4000/api/client/friend/150 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNCwiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDY0MzIsImV4cCI6MTY5OTQ1MzMzMn0.nPSTfzTA6ouPTUVoL-IFKAAdswWSB3dINnjB0t95ysY

###

# Get friends

GET http://localhost:4000/api/client/friends/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWFib3JpMkBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNTU4LCJleHAiOjE2OTk0NTg0NTh9.vbiantt_n75BpFc2FU5nKNkxsmJN-daH74_f7OLRnwU
###

# show all balance
GET http://localhost:4000/api/client/balance HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWFib3JpMkBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNzMzLCJleHAiOjE2OTk0NTg2MzN9.TN0VZtH02iWP4lgU85JfUqLVe_xw-RqGDIs6rhVAxfs
###

# Use training

DELETE  http://localhost:4000/api/client/training/110 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNCwiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDY0MzIsImV4cCI6MTY5OTQ1MzMzMn0.nPSTfzTA6ouPTUVoL-IFKAAdswWSB3dINnjB0t95ysY
###


# Post feedback

POST http://localhost:4000/api/feedbacks/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNCwiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDY0MzIsImV4cCI6MTY5OTQ1MzMzMn0.nPSTfzTA6ouPTUVoL-IFKAAdswWSB3dINnjB0t95ysY
Content-Type: application/json

{
  "trainingId": 111,
  "rating": 4,
  "text": "Вроде нормальная тренировка, но изюминки нету... Минимум 100 символов это сильно! Может учат нас печатать?"
}
###

# add Order training

POST http://localhost:4000/api/client/order HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWFib3JpMkBnbWFpbC5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNzMzLCJleHAiOjE2OTk0NTg2MzN9.TN0VZtH02iWP4lgU85JfUqLVe_xw-RqGDIs6rhVAxfs
Content-Type: application/json

{
  "type": "абонемент",
  "trainerId": 1,
  "trainingId": 1,
  "price": 12,
  "quantity": 10,
  "typeOfPayment": "visa"
}
###

# Subscribe to trainer

POST http://localhost:4000/api/client/subscribe/203 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNCwiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDc5OTMsImV4cCI6MTY5OTQ1NDg5M30.QhqEkqh4RSzF2QeJwBxO-Rpe4MlvuVE4NFHx4j2H4a0
###

# Unsubscribe to trainer

DELETE http://localhost:4000/api/client/unsubscribe/103 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNCwiZW1haWwiOiJtYWJvcmkyQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDc5OTMsImV4cCI6MTY5OTQ1NDg5M30.QhqEkqh4RSzF2QeJwBxO-Rpe4MlvuVE4NFHx4j2H4a0
###
