# Create a new user trainer
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Евгений",
  "email": "aaa2@gmail.com",
  "avatar": "avatar.jpg",
  "password": "12345a",
  "gender": "мужской",
  "birthDate": "1974-01-25T00:00:00.000Z",
  "role": "тренер",
  "description": "Сброшу ка я Вам жирок!",
  "location": "Пионерская",
  "trainer": {
    "certificate": "sertificate.pdf",
    "merits": "У меня вся грудь в орденах!",
    "isPersonalTraining": true
  },
  "level": "профессионал",
  "typesOfTraining": ["кроссфит", "бег", "бокс"]
}
###

# Create a new user client
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Евгений",
  "email": "aaa1@gmail.com",
  "avatar": "avatar.jpg",
  "password": "12345a",
  "gender": "мужской",
  "birthDate": "1974-01-25T00:00:00.000Z",
  "role": "пользователь",
  "description": "Сброшу ка я жирок!",
  "location": "Удельная",
  "client": {
  "timeOfTraining": "30-50 мин",
  "caloryLosingPlanTotal": 2000,
  "caloryLosingPlanDaily": 1000,
  "isReady": true
  },
  "level": "профессионал",
  "typesOfTraining": ["кроссфит", "бег", "бокс"]
}

###


# Update user
PATCH http://localhost:4000/api/users/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JXQstCz0LXQvdC40LkiLCJpYXQiOjE3MTEzMDM1NzIsImV4cCI6MTcxMTMwNDQ3Mn0.Bap8NWuqXWTtRT4WO3RqEzWkfJE9TNLds7k8_89gypY
ontent-Type: application/json

{
  "description": "Пять лет здесь помогаю железо таскать!"
}
###


# Login user by email and password
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "aaa@gmail.com",
  "password": "12345a"
}
###
# Get new JWT pair

POST http://localhost:4000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JXQstCz0LXQvdC40LkiLCJ0b2tlbklkIjoiODg2MmNkZTgtNzBlYi00MDBmLThkMmEtMDIyNGM4OTMxNGNmIiwiaWF0IjoxNzExMzAzNjc0LCJleHAiOjE3MTE5MDg0NzR9.rq7lQ9FYScaWFAep43OGE945Digquu4Ylu8aF4-ICY4
###

# Check user token
POST http://localhost:4000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JXQstCz0LXQvdC40LkiLCJpYXQiOjE3MTEzMDM2ODcsImV4cCI6MTcxMTMwNDU4N30.jOpbPJQhgeH7if7astD1ujoNH5BCk3Tve263s45Emi0


###

# Get user by ID
GET http://localhost:4000/api/users/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JXQstCz0LXQvdC40LkiLCJpYXQiOjE3MTEzMDM2ODcsImV4cCI6MTcxMTMwNDU4N30.jOpbPJQhgeH7if7astD1ujoNH5BCk3Tve263s45Emi0
###

# Get user  feed
GET http://localhost:4000/api/users/feed?limit=4&page=1&role=пользователь&location=Пионерская,Удельная&typesOfTraining=йога,кроссфит HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWFhQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JXQstCz0LXQvdC40LkiLCJpYXQiOjE3MTEzMDM2ODcsImV4cCI6MTcxMTMwNDU4N30.jOpbPJQhgeH7if7astD1ujoNH5BCk3Tve263s45Emi0
###
