
# Create a new training

POST http://localhost:4000/api/trainer/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFib3JpMUBnbWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNjI3LCJleHAiOjE2OTk0NTg1Mjd9.glt9N0FMb6aWINc48dOFRd1C6HUXo1FygSSV2rNKMLs
Content-Type: application/json

{
  "title": "Побегаем1!",
  "backgroundPicture": "bg-image1.jpg" ,
  "levelOfUser": "любитель",
  "typeOfTraining": "бег",
  "duration": "10-30 мин",
  "price": 5,
  "caloriesQtt": 1200,
  "description": "Пробежимся по всем достопримечательностям городского парка",
  "gender": "для мужчин",
  "video": "video.mov",
  "isPromo": true
}

###

# Update training by ID

PATCH  http://localhost:4000/api/trainer/update/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwMywiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDkwNzUsImV4cCI6MTY5OTQ1NTk3NX0.9lNNgBtVncdllkswo5_cvwI-lmzF6qk-wbG5WCeESsY
Content-Type: application/json

{
  "title": "Измененный титл",
  "price": 100
}
###

#Get training by ID

GET http://localhost:4000/api/trainer/training/211 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwMywiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTk0NDkwNzUsImV4cCI6MTY5OTQ1NTk3NX0.9lNNgBtVncdllkswo5_cvwI-lmzF6qk-wbG5WCeESsY
###

# Get trainings feed

GET  http://localhost:4000/api/trainer/feed?durations=10-30%20мин,30-50%20мин&priceMin=1&priceMax=1200&caloriesMin=1000&caloriesMax=2000&ratingMin=0&ratingMax=4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFib3JpMUBnbWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNjI3LCJleHAiOjE2OTk0NTg1Mjd9.glt9N0FMb6aWINc48dOFRd1C6HUXo1FygSSV2rNKMLs
####


# get orders
GET http://localhost:4000/api/trainer/orders?sorQtt=asc&sortPrice=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFib3JpMUBnbWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxOTY2LCJleHAiOjE2OTk0NTg4NjZ9.N5LkcgWu5wpDlGDGWnW_JqQ_Wx4SACMFWW2oqmdaBRo
###


# Get friends

GET http://localhost:4000/api/trainer/friends/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFib3JpMUBnbWFpbC5jb20iLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6ItCQ0LvQtdC60YHQtdC5IiwiaWF0IjoxNjk5NDUxNjI3LCJleHAiOjE2OTk0NTg1Mjd9.glt9N0FMb6aWINc48dOFRd1C6HUXo1FygSSV2rNKMLs
###

