
# Create a new training

POST http://localhost:4000/api/trainer/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwNiwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMTc2OTAsImV4cCI6MTY5OTAyNDU5MH0.RtuTsvsKuFarfw2_OgS3o9_z5Gy2CbEWom7KcsPt4IQ
Content-Type: application/json

{
  "title": "Побегаем4!",
  "backgroundPicture": "bg-image1.jpg" ,
  "levelOfUser": "любитель",
  "typeOfTraining": "бег",
  "duration": "10-30 мин",
  "price": 5,
  "caloriesQtt": 1200,
  "description": "Пробежимся по всем достопримечательностям городского парка",
  "gender": "для мужчин",
  "video": "video.mov",
  "isPromo": true
}

###

# Update training by ID

PATCH  http://localhost:4000/api/trainer/update/101 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNSwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMDgxODQsImV4cCI6MTY5OTAxNTA4NH0.93UlEKcISgU-MTiFNgB-r3OWX4OFezoI6r_XnIeY6Qw
Content-Type: application/json

{
  "title": "Измененный титл",
  "price": 100
}
###

#Get training by ID

GET http://localhost:4000/api/trainer/training/102 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNSwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMTAzMjgsImV4cCI6MTY5OTAxNzIyOH0.1LPk86C4oKK4zc-qd8yxVz4ESgOSQvp1jD9VAxWBOxQ
###

# Get trainings feed

GET  http://localhost:4000/api/trainer/feed?durations=10-30%20мин,30-50%20мин&priceMin=1&priceMax=1200&caloriesMin=1000&caloriesMax=2000&ratingMin=0&ratingMax=4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwNSwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMTE2MTAsImV4cCI6MTY5OTAxODUxMH0.NKcoqR44FYYB-ZqLBfcS_mFkP3eygFqFNDe5xJUi73U
####


# get orders
GET http://localhost:4000/api/trainer/orders?sorQtt=asc&sortPrice=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwNiwiZW1haWwiOiJtYWJvcmk0QGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMTc2OTAsImV4cCI6MTY5OTAyNDU5MH0.RtuTsvsKuFarfw2_OgS3o9_z5Gy2CbEWom7KcsPt4IQ
###


# Get friends

GET http://localhost:4000/api/trainer/friends/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwOCwiZW1haWwiOiJtYWJvcmkxQGdtYWlsLmNvbSIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJuYW1lIjoi0JDQu9C10LrRgdC10LkiLCJpYXQiOjE2OTkwMjA3MzYsImV4cCI6MTY5OTAyNzYzNn0.QRatCgdJQEseBQvz533RsiPXvh9voOLlBX9W-2kcdIM
###

